name: Build Voukoder

on:
  workflow_dispatch:
        
env:
  vsPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
  
jobs:
  voukoder:
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: base-devel binutils curl wget
        path-type: inherit
    - name: Set up dependencies
      shell: cmd
      run: |
        D:\a\_temp\setup-msys2\msys2.cmd -c 'curl -s https://api.github.com/repos/vouk/voukoder-ffmpeg/releases/latest | grep browser_download_url.*ffmpeg-win64-static-release | cut -d : -f 2,3 | tr -d \" | wget -i -'
#    - name: Set up MSBuild
#      uses: microsoft/setup-msbuild@v1.1
#    - name: Checkout Voukoder
#      uses: actions/checkout@v3.0.0
#      with:
#        path: project\voukoder
    - name: Build X265 (10 bit)
      shell: cmd
      run: |
        rem call "${{ env.vsPath }}VC\Auxiliary\Build\vcvars64.bat"
        dir /s 
#    - name: Publish artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: x265_10bit
#        path: dist/x265_10bit.lib
